#! /bin/bash -l

#SBATCH --job-name=RoH_Het
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --time=120:00:00
#SBATCH --mem=125G
#SBATCH --error=logs/RoH_Het.%J.err
#SBATCH --output=logs/RoH_Het.%J.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=feiner@evolbio.mpg.de
#SBATCH --partition=standard

### To obtain Runs of Homozygosity using bcftools and plink and calculate the FROH for each sample (inbreeding coefficient)

# Note that the script needs to be adapted to run on a cluster by either loading the right modules (on Dardel) or by giving the right path to executables (on Wallace)
# Export path to bcftools:
export PATH=/data/biosoftware/bcftools/bcftools-1.21/:$PATH

# VCF file with variant and invariant sites needs to be declared; this has been filtered to exclude sites with any missing genotypes and is used for RoH estimation

VCF=/home/feiner/Projects/UKwallies/Datasets/AllSites_VCFs/All_French_final.vcf.gz

# A file with the samples' names needs to be declared (incl. outgroup)
samples_list=/home/feiner/Projects/UKwallies/scripts/French_samples

# The size cut-off for RoH is declared
RoH_size_num=500000
RoH_size_nam=500kb

mkdir -p /home/feiner/Projects/UKwallies/Results_RoH_Het_FR/500kb
cd /home/feiner/Projects/UKwallies/Results_RoH_Het_FR/500kb

#### Add a fictitious fully homozygous sample (Ppi_Hz) to calculate the length of the homozygous genome
# copy the header
zcat ${VCF} | head -n 10000 | grep "^#" > head.tmp
# add new sample name
sed -i '$ s/$/\tPxx_Hz/' head.tmp
# add 0/0 genotypes
zcat ${VCF} | grep -v "^#" | sed -e 's/$/\t0\/0/g' | cat head.tmp - | bgzip > ${VCF}_pseudo
rm head.tmp

#### BCFTOOLS
# -e tells it to estimate frequencies based only on the actual samples - not the fictitious one
bcftools roh ${VCF}_pseudo -e ${samples_list} -G 30 -O r -o roh.pseudo
# quality filters: Phred score > 50 & length > 1 Mb
cat roh.pseudo | awk '$8 > 50' > roh.pseudo.qual
awk -v minsize="$RoH_size_num" '$6 > minsize' roh.pseudo.qual > roh.pseudo.qual.${RoH_size_nam}

#### Calculate FRoH for each sample: (sum of ROHs > minsize)/(length of homozygous genome) and export relevant data
#Calculate length of the homozygous genome
homlength=$(grep "Pxx_Hz" roh.pseudo.qual.${RoH_size_nam} | awk '{sum += $6} END {print sum}')
out="froh_summary_bcftools_FR_${RoH_size_nam}.txt"
echo -e "Sample\tFRoH\tLength\tnRoH" > "$out"
while read -r sample; do
    [ -z "$sample" ] && continue

    # Sum of ROH lengths for this sample
    sum=$(awk -v s="$sample" '$2 == s {total += $6} END {print total+0}' roh.pseudo.qual.${RoH_size_nam})

    # Count number of ROH segments for this sample
    count=$(awk -v s="$sample" '$2 == s {n++} END {print n+0}' roh.pseudo.qual.${RoH_size_nam})

    # Calculate FROH
    ratio=$(awk -v a="$sum" -v b="$homlength" 'BEGIN {
        if (b > 0) printf "%.6f", a / b;
        else print "NA"
    }')
    echo -e "${sample}\t${ratio}\t${sum}\t${count}" >> "$out"
done < "$samples_list"
